### ISSUE TITLE
Demo: Search -> Show Form doesn't change selected form in sidebar/side-panel 

### ISSUE THREAD

**Issue by sipsuru** [DJ-Raven/swing-modal-dialog#11]
**Title**: Search -> Show Form doesn't change selected form in sidebar/side-panel 

**Description**:  
When we search and select a form through search panel, the selected form item doesn't change in drawer.

**Steps to Reproduce**:
1. Go to the search field.
2. Enter a term (ex: Toast)
3. Click on the result. 

The form opens / shows but the selected item doesn't change in sidebar

Ex:

https://github.com/user-attachments/assets/1fd1933e-3b58-4f86-9bef-55b3a1b7d26a

**Expected Behavior**:  
When a form opens / shows the selected items from the sidebar should update

**Comment by DJ-Raven** [comment]
I has updated. now current on `update-menu-option` branch. But I need test a few more days before merge to `main` branch

**Comment by sipsuru** [comment]
Thank you for the update!

I see that the issue is resolved in the `update-menu-option` branch, and it works for me as well. 

Great work! (As always)
