### ISSUE TITLE
Change drawer Icon, title Description 

### ISSUE THREAD

**Issue by XCodeSonic** [DJ-Raven/swing-modal-dialog#20]
How can I change the drawer icon, title and description if the user is Admin or not admin, hide some menu

**Comment by DJ-Raven** [comment]
I has add new test form for menu validation you can check this commit : https://github.com/DJ-Raven/swing-modal-dialog/commit/9078ba81d189c0dc2330fe60d45348d6d2047c03

**Comment by DJ-Raven** [comment]
This for change icon, title, and description
https://github.com/DJ-Raven/swing-modal-dialog/blob/9078ba81d189c0dc2330fe60d45348d6d2047c03/demo/src/test/java/test/validation/ValidationDrawerBuilder.java#L33-L45

And this validation the menu item
https://github.com/DJ-Raven/swing-modal-dialog/blob/9078ba81d189c0dc2330fe60d45348d6d2047c03/demo/src/test/java/test/validation/ValidationDrawerBuilder.java#L147-L178
