### ISSUE TITLE
Toast location

### ISSUE THREAD

**Issue by MhmdSAbdlh** [DJ-Raven/swing-modal-dialog#21]
Can you add an option to open the toast from the button position, or from custom X,Y from the frame?

**Comment by DJ-Raven** [comment]
Updated. see this PR #22
You can use this in `2.2.0-SNAPSHOT`: https://github.com/DJ-Raven/swing-modal-dialog#snapshots

It not support location related to another component.
But you can use the `SwingUtilities.convertPoint` method

``` java
// get the location of button cmdShow
Point location = SwingUtilities.convertPoint(cmdShow.getParent(), cmdShow.getLocation(), this.getContentPane());

// create toast option
ToastOption toastOption = Toast.createOption();

// set location
toastOption.getLayoutOption()
        .setLocation(location.x, location.y)
        .setDirection(ToastDirection.TOP_TO_BOTTOM);

// show toast
Toast.show(this, Toast.Type.SUCCESS, "Success message", toastOption);
```

**Comment by MhmdSAbdlh** [comment]
Thanks, and the toastdirection is awesome!
