### ISSUE TITLE
Demo: Inconsistent Search Case Sensitivity

### ISSUE THREAD

**Issue by sipsuru** [DJ-Raven/swing-modal-dialog#9]
**Title**: Make search functionality case-insensitive

**Description**:  
Currently, the search functionality in the `search()` method is case-sensitive. This causes inconsistent search results when users enter a search term with a different case than the stored names or descriptions. To improve user experience, the search should be made case-insensitive.

**Steps to Reproduce**:
1. Go to the search field.
2. Enter a term with uppercase or mixed case (e.g., `Toast`).

It won’t match. 

Ex:

https://github.com/user-attachments/assets/80fda7b1-f2ae-4277-8fad-0eff89b9c077

**Expected Behavior**:  
The search should return results regardless of case (e.g., entering `ToaSt` or `toast` should return the same result).

**Suggested Fix**:  
To make the search case-insensitive, both the search term and the form’s name and description should be converted to lowercase before comparison.

**Relevant Code**:  
In the `search()` method:
```java
String st = textSearch.getText().trim().toLowerCase(); // Convert search term to lowercase 
```

Ensures both the search term and the fields being compared (s.name(), s.description(), etc.) are converted to lowercase for comparison.

**Additional Context**:
But I guess that the ```text``` string that is compared to ```st``` is the description of the Form. If I'm correct in this case, it'd be better if we can search from both title and description.

**Comment by DJ-Raven** [comment]
Thank again :)
